# Generated by Django 5.2.2 on 2025-06-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=56, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=56, null=True)),
                ('student_imeg', models.ImageField(upload_to='static/media/')),
                ('student_id_number', models.TextField(unique=True)),
                ('email', models.CharField(max_length=86)),
                ('passport_number', models.TextField()),
                ('birth_date', models.TextField()),
                ('groups', models.JSONField()),
                ('studentStatus', models.TextField()),
                ('paymentForm', models.TextField()),
                ('faculty', models.TextField()),
                ('level', models.TextField()),
                ('avg_gpa', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
