# Generated by Django 5.2.2 on 2025-06-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avg_gpa',
            field=models.CharField(max_length=86),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(max_length=86),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=86),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='paymentForm',
            field=models.CharField(max_length=86),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentStatus',
            field=models.CharField(max_length=86),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
