# Generated by Django 5.1.1 on 2025-06-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand', '0002_alter_student_avg_gpa_alter_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_imeg',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
