# Generated by Django 5.2.2 on 2025-06-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand', '0003_criteria_alter_student_student_imeg_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfiles',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
