# Generated by Django 5.1.1 on 2025-06-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grand', '0003_alter_student_student_imeg'),
        ('grand', '0004_studentfiles_supervisor_comment'),
    ]

    operations = [
    ]
