# Generated by Django 5.2.2 on 2025-06-09 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand', '0005_merge_20250609_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=56),
            preserve_default=False,
        ),
    ]
