# Generated by Django 5.2.2 on 2025-07-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grand', '0006_criteria_description_alter_criteria_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentfiles',
            unique_together={('student', 'criteria')},
        ),
    ]
