# Generated by Django 5.2.2 on 2025-07-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand', '0007_alter_studentfiles_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfiles',
            name='is_scored',
            field=models.BooleanField(default=False, verbose_name='Baholandi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avg_gpa',
            field=models.CharField(max_length=86, verbose_name='Gpa-bali'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.CharField(max_length=50, verbose_name="Tug'ilgan-kun-sanasi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(max_length=86, verbose_name='fakultet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=86, verbose_name='kurs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(max_length=12, verbose_name='passport raqami'),
        ),
        migrations.AlterField(
            model_name='student',
            name='paymentForm',
            field=models.CharField(max_length=86, verbose_name="to'lov shakli"),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Telfon-raqam'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentStatus',
            field=models.CharField(max_length=86, verbose_name='talaba-holati'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_imeg',
            field=models.ImageField(upload_to='media/', verbose_name='rasm'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Talaba_Ismi'),
        ),
    ]
